### ISSUE TITLE
React.createClass || extends React.Component

### ISSUE THREAD

**Issue by agiannastasio** [joshwnj/react-starter#1]
As a React beginner, I'm not getting the difference between these two (except for the syntax).
@joshwnj, did you use `React.createClass` for any particular reason?

**Comment by joshwnj** [comment]
Good question.

The answer is that they _pretty much_ do the same, but with a few subtle differences. The reason I've chosen `React.createClass` in this case is that I think there are a few less things that you need to know.

Once you're familiar with that, you can easily switch over to the `class Foo extends Component` syntax if you need to.
