### ISSUE TITLE
Tutorial 2 - passing actions to the functional component

### ISSUE THREAD

**Issue by mccrodp** [joshwnj/react-starter#5]
As mentioned in another question I believe, most examples are based on React.Component, so I read [React.createClass versus extends React.Component](https://toddmotto.com/react-create-class-versus-component/).

Most of the examples I've found incl. some of our internal apps on this are using Redux for state / reducers for actions, etc. I'm having trouble identifying what documentation I should be reading for this. Am I trying to "pass actions to a functional component"?

One of our internal apps is more similar to this and I believe we may need to `import` the actions from the other component `import * as actions from 'actions'` and then access via `actions.functionName()`, but just looking for clarification on the most fundamental method to achieve the end goal here.

I've commit [what I have so far](https://github.com/mccrodp/react-starter/tree/tutorial-2-start), but it's a bit bare as most of the work so far was research. Appreciate any tips or documentation links relevant for this example without Redux and the extra baggage. 

Thanks @joshwnj!

**Comment by mccrodp** [comment]
Hoping to get another look at this tutorial next week if you get a chance to look at this sometime next week @joshwnj, that would be a great help with that. Cheers!

**Comment by joshwnj** [comment]
> Most of the examples I've found incl. some of our internal apps on this are using Redux for state

Yes, you can consider this tutorial kind of a precursor to redux. I haven't mentioned redux but a lot of the same principles apply. Once you're familiar with this approach in plain react (working with "container" components and "pure" components) you'll be right at home switching to redux, as it just bundles up a lot of this stuff for you. But it's helpful to know what is happening behind the scenes.

A couple of things to look into further:

```
<Component {...this.state} {...this.actions} />
```

this syntax says:

- take everything from `this.state`
- take everything from `this.actions`
- apply them as props to the component (if there are any duplicate keys, the last one wins).

So within `Component`, you won't get `(props, actions)`, you'll just get `(props)`.

Take a look at the `tutorial-2-end` branch and let me know if you have any questions around that - maybe we can clear it up for future people :)

**Comment by mccrodp** [comment]
I've just gone through the solution and it makes more sense now. For me it feels quite involved for a beginner, but a good task none the less and especially for a seasoned JS dev. I feel for me to have gotten more out of the task myself with limited time, I would have needed some more direction or hints. I've outlined some items below where I may have benefited from hints and also some parts I'd like to clarify my understanding before starting Part 3.

## Only props get sent to the component
>you won't get (props, actions), you'll just get (props)

^ This is a big change in my comprehension of what's happening, you can only ever pass anything via props. Understood.

Maybe : changing "and pass them into the pure component." to "and pass them into the pure component (hint: as props)." just to make Googling easier.

## Event handlers
Other items that were of surprise to me were seeing the `function (e)`, something I remember from plain JS, the `e` event. I thought React may have had a more "React" way of doing this, but it's fundamental and makes sense. I missed it entirely though in my solution. Maybe it could be made more clear, it maybe obvious to most JS devs, but maybe not for others.

"So find a way to define callbacks" to "So find a way to define callbacks (hint: use event handlers / anonymous fns in stateful component)" <- not sure of the best way to describe technically

## Preventing default functionality on submit
Maybe the `e.preventDefault()` on the Submit could also exist as a hint.

## Sending props to the component
In the render function we have:

````jsx
render: function () {
    return <Component {...this.state}
      onTextChange={this.onTextChange}
      onCheckboxChange={this.onCheckboxChange}
      onSubmit={this.onSubmit}
      />
  }
````
I need a bit of clarification on this, the component is setting a custom variable `onTextChange=` to the current state's onTextChange property via : `this.onTextChange` which is accessed in the main component as a prop via `props.onTextChange`, is that correct?

## Calling `this.setState`

I notice that `getInitialState` does not call `this.setState` whereas the other methods of our class do. I presume then that `getInitialState` does in fact call set state indirectly elsewhere. Perhaps calling `this.setState` could exist as a hint also.

---

Maybe those hints could live separately in a `hints.md` file on `tutorial-2-start` branch for people if they get stuck as I did. I probably would have gotten some of these if I had more time to dedicate to the tutorial though in fairness, but I'm sure others will be in the same boat too.

Cheers, roll on part 3! 😄

**Comment by joshwnj** [comment]
Thanks, that's good feedback. It's always hard to know where to target a tutorial, and what prior knowledge to assume. _"If you want to make an apple pie from scratch, first you have to create the universe"_ comes to mind :)

With this tutorial, I'm happy to leave some parts out and encourage people to ask questions here in Issues, like you've done - the idea being that those who have gone through the tutorial themselves will be able to help answer those questions for others :)

> I need a bit of clarification on this, the component is setting a custom variable onTextChange= to the current state's onTextChange property via : this.onTextChange which is accessed in the main component as a prop via props.onTextChange, is that correct?

I can see how this is confusing :) Let me try to unwind it:

1. the **stateful component** is in charge of **data interactions**, not knowing how they will be displayed.
2. the **pure component** is in charge of **displaying the data and triggering interactions**, not knowing how they work or where the data comes from.

This is a wonderful separation of concerns, and lends itself to easier testing, debugging and refactoring.

- so the stateful component defines the `onTextChange` function, because it knows what should happen to the data when text changes.
- but the stateful component doesn't know how the data will be rendered, so it passes this function into the pure component.
- the pure component receives the function as a prop, and says _"call `props.onTextChange` whenever the `<input>` element fires an onChange event"_.  It doesn't know or care what that function actually does.

Does that clear it up? Or still some questions in the air?

> I notice that getInitialState does not call this.setState whereas the other methods of our class do. I presume then that getInitialState does in fact call set state indirectly elsewhere. Perhaps calling this.setState could exist as a hint also.

`getInitialState` doesn't call `setState`, because it actually sets the initial value of `state`: https://github.com/facebook/react/blob/master/src/isomorphic/classic/class/ReactClass.js#L757-L774

**Comment by mccrodp** [comment]
>It's always hard to know where to target a tutorial, and what prior knowledge to assume. "If you want to make an apple pie from scratch, first you have to create the universe" comes to mind :)

Absolutely! Actually, the style you have makes a lot of sense now then without the hints, and just inviting discussion via issues, it's more by design 😄 

>getInitialState doesn't call setState, because it actually sets the initial value of state

Ah-ha, I should have thought of that 😛 👍 

Thanks for the detailed follow up, going to digest it in more detail tomorrow and get back if I've any follow ups.

**Comment by mccrodp** [comment]
>Does that clear it up? Or still some questions in the air?

That does clear things up, it is different to what I imagined, but I understand now the line that was confusing me `onTextChange={this.onTextChange}`. We are creating a prop `onTextChange` and passing the whole `this.onTextChange` method as part of that prop. 

Thanks a lot for that, I'm sure this understanding will help me a lot in other projects 😄

**Comment by joshwnj** [comment]
> We are creating a prop onTextChange and passing the whole this.onTextChange method as part of that prop

exactly! nicely done :)
